/* Independent project coverflow; uses existing portfolio artwork without modifying Crafted Gallery. */
(()=>{const root=document.getElementById('voyageCraftGallery');if(!root)return;
const wrap=document.getElementById('voyageCraftCards'),backdrop=root.querySelector('.crafted-voyage-backdrop'),title=document.getElementById('voyageCraftTitle'),kicker=document.getElementById('voyageCraftKicker'),subtitle=document.getElementById('voyageCraftSubtitle'),count=document.getElementById('voyageCraftCount'),progress=document.getElementById('voyageCraftProgress');
const items=[
{title:'GOOGLE ADS',kicker:'CAMPAIGN · CREATIVE',sub:'DESIGNED TO MAKE AN IMPACT',image:'ac094c3fedd25880080e0f0e4d5b7467.jpg'},
{title:'PRODUCT ADS',kicker:'PRODUCT · E-COMMERCE',sub:'MADE TO STOP THE SCROLL',image:'honey.jpg'},
{title:'BRANDING',kicker:'IDENTITY · ART DIRECTION',sub:'A DISTINCTIVE VISUAL LANGUAGE',image:'dharmi-realty.jpg'},
{title:'VISUAL EXPERIMENTS',kicker:'CONCEPT · COMPOSITION',sub:'IDEAS TURNED INTO VISUALS',image:'port 7.jpg'},
{title:'MOTION GRAPHICS',kicker:'MOTION · STORYTELLING',sub:'DESIGN THAT COMES ALIVE',image:'followes.jpg'},
{title:'FOOD CAMPAIGNS',kicker:'FOOD · PROMOTION',sub:'BUILT TO LOOK IRRESISTIBLE',image:'momo-street.jpg'}];
let active=0,startX=0,dragging=false;
items.forEach((item,i)=>{const card=document.createElement('button');card.type='button';card.className='voyage-craft-card';card.setAttribute('aria-label','View '+item.title);const img=document.createElement('img');img.src=item.image;img.alt=item.title;img.loading=i<3?'eager':'lazy';const label=document.createElement('span');label.className='voyage-craft-label';label.textContent=item.title;card.append(img,label);card.addEventListener('click',()=>{if(i===active){const imgUrl=item.image;window.open(imgUrl,'_blank','noopener');}else setActive(i)});wrap.append(card)});
const cards=[...wrap.children];
function setActive(i){active=(i+items.length)%items.length;const w=root.querySelector('.crafted-voyage-stage').clientWidth;cards.forEach((card,n)=>{let d=n-active;while(d>items.length/2)d-=items.length;while(d< -items.length/2)d+=items.length;const x=d*w*.235;const rotate=d===0?0:(d<0?1:-1)*Math.min(52,Math.abs(d)*27);const scale=d===0?1:Math.max(.65,1-Math.abs(d)*.12);card.style.transform='translate(-50%,-50%) translateX('+x+'px) translateZ('+(-Math.abs(d)*115)+'px) rotateY('+rotate+'deg) scale('+scale+')';card.style.opacity=Math.abs(d)>2?'0':String(1-Math.abs(d)*.18);card.style.zIndex=String(20-Math.abs(d));card.classList.toggle('is-active',d===0);card.tabIndex=Math.abs(d)<=1?0:-1;});const p=items[active];title.textContent=p.title;kicker.textContent=p.kicker;subtitle.textContent=p.sub;count.textContent=String(active+1).padStart(2,'0')+' / '+String(items.length).padStart(2,'0');progress.style.width=((active+1)/items.length*100)+'%';backdrop.style.backgroundImage='url("'+p.image.replace(/"/g,'')+'")';}
root.querySelector('.crafted-voyage-prev').addEventListener('click',()=>setActive(active-1));root.querySelector('.crafted-voyage-next').addEventListener('click',()=>setActive(active+1));
root.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')setActive(active-1);if(e.key==='ArrowRight')setActive(active+1)});
const stage=root.querySelector('.crafted-voyage-stage');stage.addEventListener('pointerdown',e=>{startX=e.clientX;dragging=true});stage.addEventListener('pointerup',e=>{if(!dragging)return;const dx=e.clientX-startX;if(Math.abs(dx)>45)setActive(active+(dx<0?1:-1));dragging=false});stage.addEventListener('pointercancel',()=>dragging=false);
let resize;window.addEventListener('resize',()=>{clearTimeout(resize);resize=setTimeout(()=>setActive(active),100)});setActive(0);
})();